export const books = [
    { id: 1, src: 'loonshots-cover', alt: 'Loonshots cover', title: 'Loonshots', author: 'Safi Bahchall' },
    { id: 2, src: 'kitchen-confidential-cover', alt: 'Kitchen Confidential cover', title: 'Kitchen Confidential', author: 'Anthony Bourdain' },
    { id: 3, src: 'ishmael-cover', alt: 'Ishmael cover', title: 'Ishmael', author: 'Daniel Quinn' },
    { id: 4, src: 'meditations-cover', alt: 'Meditations cover', title: 'Meditations', author: 'Marcus Aurelius' },
    { id: 5, src: 'power-of-broke-cover', alt: 'The Power of Broke cover', title: 'The Power of Broke', author: 'Daymond John with Daniel Paisner' },
    { id: 6, src: 'outliers-cover', alt: 'Outliers cover', title: 'Outliers', author: 'Malcolm Gladwell' },
    { id: 7, src: 'who-is-michael-ovitz-cover', alt: 'Who Is Michael Ovitz cover', title: 'Who Is Michael Ovitz', author: 'Michael Ovitz' },
    { id: 8, src: 'the-lean-startup-cover', alt: 'The Lean Startup cover', title: 'The Lean Startup', author: 'Eric Ries' },
    { id: 9, src: 'greenlights-cover', alt: 'Greenlights cover', title: 'Greenlights', author: 'Matthew McConaughey' },
    { id: 10, src: 'too-big-to-fail-cover', alt: 'Too Big to Fail cover', title: 'Too Big to Fail', author: 'Andrew Ross Sorkin' },
    { id: 11, src: 'stories-of-your-life-and-others-cover', alt: 'Stories of Your Life and Others cover', title: 'Stories of Your Life and Others', author: 'Ted Chiang' },
    { id: 12, src: 'how-to-win-friends-cover', alt: 'How to Win Friends and Influence People cover', title: 'How to Win Friends and Influence People', author: 'Dale Carnegie' },
    { id: 13, src: 'mans-search-for-meaning-cover', alt: 'Man\'s Search for Meaning cover', title: 'Man\'s Search for Meaning', author: 'Viktor Frankl' },
    { id: 14, src: 'thing-explainer-cover', alt: 'Thing Explainer cover', title: 'Thing Explainer', author: 'Randall Monroe' },
    { id: 15, src: 'the-art-of-simple-living-cover', alt: 'The Art of Simple Living cover', title: 'The Art of Simple Living', author: 'Shunmyo Masuno' },
    { id: 16, src: 'how-to-castrate-a-bull-cover', alt: 'How to Castrate a Bull cover', title: 'How to Castrate a Bull', author: 'Dave Hitz' },
    { id: 17, src: 'siddhartha-cover', alt: 'Siddhartha cover', title: 'Siddhartha', author: 'Hermann Hesse' },
    { id: 18, src: 'rafa-cover', alt: 'Rafa cover', title: 'Rafa', author: 'Rafael Nadal and John Carlin' },
    { id: 19, src: 'down-and-out-in-paris-and-london-cover', alt: 'Down and Out in Paris and London cover', title: 'Down and Out in Paris and London', author: 'George Orwell' },
    { id: 20, src: 'running-with-the-buffaloes-cover', alt: 'Running with the Buffaloes cover', title: 'Running with the Buffaloes', author: 'Chris Lear' },
    { id: 21, src: 'sapiens-cover', alt: 'Sapiens cover', title: 'Sapiens', author: 'Yuval Noah Harari' },
    { id: 22, src: 'zen-and-the-art-of-motorcycle-maintenance-cover', alt: 'Zen and the Art of Motorcycle Maintenance cover', title: 'Zen and the Art of Motorcycle Maintenance', author: 'Robert M. Pirsig' },
    { id: 23, src: 'paul-newman-cover', alt: 'The Extraordinary Life of an Ordinary Man cover', title: 'The Extraordinary Life of an Ordinary Man', author: 'Paul Newman' },
    { id: 24, src: 'the-great-stagnation-cover', alt: 'The Great Stagnation cover', title: 'The Great Stagnation', author: 'Tyler Cowen' },
    { id: 25, src: 'hitchhikers-guide-to-the-galaxy-cover', alt: 'The Hitchhiker\'s Guide to the Galaxy cover', title: 'The Hitchhiker\'s Guide to the Galaxy', author: 'Douglas Adams' },
    { id: 26, src: 'the-founders-paypal-cover', alt: 'The Founders cover', title: 'The Founders', author: 'Jimmy Soni' },
    { id: 27, src: 'yearbook-cover', alt: 'Yearbook cover', title: 'Yearbook', author: 'Seth Rogen' },
    { id: 28, src: 'let-my-people-go-surfing-cover', alt: 'Let My People Go Surfing cover', title: 'Let My People Go Surfing', author: 'Yvon Chouinard' },
    { id: 29, src: 'the-last-mogul-cover', alt: 'The Last Mogul cover', title: 'The Last Mogul', author: 'Dennis McDougal' },
    { id: 30, src: 'what-we-owe-the-future-cover', alt: 'What We Owe the Future cover', title: 'What We Owe the Future', author: 'William MacAskill' },
    { id: 31, src: 'the-godfather-cover', alt: 'The Godfather cover', title: 'The Godfather', author: 'Mario Puzo' },
    { id: 32, src: 'the-alchemist-cover', alt: 'The Alchemist cover', title: 'The Alchemist', author: 'Paulo Coelho' },
    { id: 33, src: 'flash-boys-cover', alt: 'Flash Boys cover', title: 'Flash Boys', author: 'Michael Lewis' },
    { id: 34, src: 'thousand-mile-summer-cover', alt: 'The Thousand-Mile Summer cover', title: 'The Thousand-Mile Summer', author: 'Colin Fletcher' },
]