export const books = [
    { id: 1, src: 'loonshots-cover', alt: 'Loonshots cover', title: 'Loonshots', author: 'Safi Bahchall', link: 'https://www.goodreads.com/en/book/show/39863447' },
    { id: 2, src: 'kitchen-confidential-cover', alt: 'Kitchen Confidential cover', title: 'Kitchen Confidential', author: 'Anthony Bourdain', link: 'https://www.goodreads.com/book/show/33313.Kitchen_Confidential' },
    { id: 3, src: 'ishmael-cover', alt: 'Ishmael cover', title: 'Ishmael', author: 'Daniel Quinn', link: 'https://www.goodreads.com/en/book/show/40611328' },
    { id: 4, src: 'meditations-cover', alt: 'Meditations cover', title: 'Meditations', author: 'Marcus Aurelius', link: 'https://www.goodreads.com/book/show/30659.Meditations' },
    { id: 5, src: 'power-of-broke-cover', alt: 'The Power of Broke cover', title: 'The Power of Broke', author: 'Daymond John with Daniel Paisner', link: 'https://www.goodreads.com/en/book/show/25430691' },
    { id: 6, src: 'outliers-cover', alt: 'Outliers cover', title: 'Outliers', author: 'Malcolm Gladwell', link: 'https://www.goodreads.com/book/show/3228917-outliers' },
    { id: 7, src: 'who-is-michael-ovitz-cover', alt: 'Who Is Michael Ovitz cover', title: 'Who Is Michael Ovitz', author: 'Michael Ovitz', link: 'https://www.goodreads.com/en/book/show/40092129' },
    { id: 8, src: 'the-lean-startup-cover', alt: 'The Lean Startup cover', title: 'The Lean Startup', author: 'Eric Ries', link: 'https://www.goodreads.com/en/book/show/10127019' },
    { id: 9, src: 'greenlights-cover', alt: 'Greenlights cover', title: 'Greenlights', author: 'Matthew McConaughey', link: 'https://www.goodreads.com/en/book/show/52838315' },
    { id: 10, src: 'too-big-to-fail-cover', alt: 'Too Big to Fail cover', title: 'Too Big to Fail', author: 'Andrew Ross Sorkin', link: 'https://www.goodreads.com/book/show/6687247-too-big-to-fail' },
    { id: 11, src: 'stories-of-your-life-and-others-cover', alt: 'Stories of Your Life and Others cover', title: 'Stories of Your Life and Others', author: 'Ted Chiang', link: 'https://www.goodreads.com/book/show/223380.Stories_of_Your_Life_and_Others' },
    { id: 12, src: 'how-to-win-friends-cover', alt: 'How to Win Friends and Influence People cover', title: 'How to Win Friends and Influence People', author: 'Dale Carnegie', link: 'https://www.goodreads.com/book/show/4865.How_to_Win_Friends_and_Influence_People' },
    { id: 13, src: 'mans-search-for-meaning-cover', alt: 'Man\'s Search for Meaning cover', title: 'Man\'s Search for Meaning', author: 'Viktor Frankl', link: 'https://www.goodreads.com/en/book/show/4069' },
    { id: 14, src: 'thing-explainer-cover', alt: 'Thing Explainer cover', title: 'Thing Explainer', author: 'Randall Monroe', link: 'https://www.goodreads.com/book/show/25329850-thing-explainer' },
    { id: 15, src: 'the-art-of-simple-living-cover', alt: 'The Art of Simple Living cover', title: 'The Art of Simple Living', author: 'Shunmyo Masuno', link: 'https://www.goodreads.com/en/book/show/41081321' },
    { id: 16, src: 'how-to-castrate-a-bull-cover', alt: 'How to Castrate a Bull cover', title: 'How to Castrate a Bull', author: 'Dave Hitz', link: 'https://www.goodreads.com/en/book/show/5489335' },
    { id: 17, src: 'siddhartha-cover', alt: 'Siddhartha cover', title: 'Siddhartha', author: 'Hermann Hesse', link: 'https://www.goodreads.com/book/show/52036.Siddhartha' },
    { id: 18, src: 'rafa-cover', alt: 'Rafa cover', title: 'Rafa', author: 'Rafael Nadal and John Carlin', link: 'https://www.goodreads.com/en/book/show/10746419' },
    { id: 19, src: 'down-and-out-in-paris-and-london-cover', alt: 'Down and Out in Paris and London cover', title: 'Down and Out in Paris and London', author: 'George Orwell', link: 'https://www.goodreads.com/en/book/show/393199' },
    { id: 20, src: 'running-with-the-buffaloes-cover', alt: 'Running with the Buffaloes cover', title: 'Running with the Buffaloes', author: 'Chris Lear', link: 'https://www.goodreads.com/en/book/show/125912' },
    { id: 21, src: 'sapiens-cover', alt: 'Sapiens cover', title: 'Sapiens', author: 'Yuval Noah Harari', link: 'https://www.goodreads.com/en/book/show/23692271' },
    { id: 22, src: 'zen-and-the-art-of-motorcycle-maintenance-cover', alt: 'Zen and the Art of Motorcycle Maintenance cover', title: 'Zen and the Art of Motorcycle Maintenance', author: 'Robert M. Pirsig', link: 'https://www.goodreads.com/en/book/show/629' },
    { id: 23, src: 'paul-newman-cover', alt: 'The Extraordinary Life of an Ordinary Man cover', title: 'The Extraordinary Life of an Ordinary Man', author: 'Paul Newman', link: 'https://www.goodreads.com/en/book/show/60190681' },
    { id: 24, src: 'the-great-stagnation-cover', alt: 'The Great Stagnation cover', title: 'The Great Stagnation', author: 'Tyler Cowen', link: 'https://www.goodreads.com/en/book/show/10276354' },
    { id: 25, src: 'hitchhikers-guide-to-the-galaxy-cover', alt: 'The Hitchhiker\'s Guide to the Galaxy cover', title: 'The Hitchhiker\'s Guide to the Galaxy', author: 'Douglas Adams', link: 'https://www.goodreads.com/book/show/11.The_Hitchhiker_s_Guide_to_the_Galaxy' },
    { id: 26, src: 'the-founders-paypal-cover', alt: 'The Founders cover', title: 'The Founders', author: 'Jimmy Soni', link: 'https://www.goodreads.com/en/book/show/54304287' },
    { id: 27, src: 'yearbook-cover', alt: 'Yearbook cover', title: 'Yearbook', author: 'Seth Rogen', link: 'https://www.goodreads.com/book/show/44678031-yearbook' },
    { id: 28, src: 'let-my-people-go-surfing-cover', alt: 'Let My People Go Surfing cover', title: 'Let My People Go Surfing', author: 'Yvon Chouinard', link: 'https://www.goodreads.com/en/book/show/22155' },
    { id: 29, src: 'the-last-mogul-cover', alt: 'The Last Mogul cover', title: 'The Last Mogul', author: 'Dennis McDougal', link: 'https://www.goodreads.com/en/book/show/411717' },
    { id: 30, src: 'what-we-owe-the-future-cover', alt: 'What We Owe the Future cover', title: 'What We Owe the Future', author: 'William MacAskill', link: 'https://www.goodreads.com/en/book/show/59802037' },
    { id: 31, src: 'the-godfather-cover', alt: 'The Godfather cover', title: 'The Godfather', author: 'Mario Puzo', link: 'https://www.goodreads.com/en/book/show/22034' },
    { id: 32, src: 'the-alchemist-cover', alt: 'The Alchemist cover', title: 'The Alchemist', author: 'Paulo Coelho', link: 'https://www.goodreads.com/book/show/18144590-the-alchemist' },
    { id: 33, src: 'flash-boys-cover', alt: 'Flash Boys cover', title: 'Flash Boys', author: 'Michael Lewis', link: 'https://www.goodreads.com/book/show/24724602-flash-boys' },
    { id: 34, src: 'thousand-mile-summer-cover', alt: 'The Thousand-Mile Summer cover', title: 'The Thousand-Mile Summer', author: 'Colin Fletcher', link: 'https://www.goodreads.com/book/show/731249.The_Thousand_Mile_Summer' },
    { id: 35, src: 'shoe-dog-cover', alt: 'Shoe Dog cover', title: 'Shoe Dog', author: 'Phil Knight', link: 'https://www.goodreads.com/en/book/show/27220736' },
    { id: 36, src: 'brave-new-world-cover', alt: 'Brave New World cover', title: 'Brave New World', author: 'Aldous Huxley', link: 'https://www.goodreads.com/book/show/5129.Brave_New_World' },
]